{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shared-alb-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.annotations."alb.ingress.kubernetes.io/scheme" }}
    alb.ingress.kubernetes.io/target-type: {{ .Values.ingress.annotations."alb.ingress.kubernetes.io/target-type" }}
    alb.ingress.kubernetes.io/backend-protocol: {{ .Values.ingress.annotations."alb.ingress.kubernetes.io/backend-protocol" }}
    alb.ingress.kubernetes.io/listen-ports: {{ .Values.ingress.annotations."alb.ingress.kubernetes.io/listen-ports" | quote }}
    alb.ingress.kubernetes.io/healthcheck-protocol: {{ .Values.ingress.annotations."alb.ingress.kubernetes.io/healthcheck-protocol" }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.ingress.annotations."alb.ingress.kubernetes.io/healthcheck-path" }}
    alb.ingress.kubernetes.io/success-codes: {{ .Values.ingress.annotations."alb.ingress.kubernetes.io/success-codes" | quote }}
    alb.ingress.kubernetes.io/load-balancer-name: {{ .Values.ingress.albName }}
    alb.ingress.kubernetes.io/group.name: {{ .Values.ingress.albGroup }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - http:
        paths:
          {{- range .Values.ingress.rules }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .serviceName }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
{{- end }}
