name: Terraform Deploy (EKS)

on:
  pull_request:
    branches: ["main", "dev", "qa"]
    types: [opened]
  push:
    branches:
      - rc/*

permissions:
  id-token: write        # Required for GitHub OIDC auth
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_DEV }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=infra init

      - name: Terraform Validate
        run: terraform -chdir=infra validate

      - name: Terraform Plan
        run: terraform -chdir=infra plan

      - name: Terraform destroy
        if: github.event_name == 'push'
        run: terraform -chdir=infra destroy -auto-approve
